// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALK_2Z_Wa5kN2T6zf-fhJqaNRGHJ_b_uc',
    appId: '1:743191976125:web:0aaf37f0afff15536dbfd4',
    messagingSenderId: '743191976125',
    projectId: 'special-love-fa3eb',
    authDomain: 'special-love-fa3eb.firebaseapp.com',
    storageBucket: 'special-love-fa3eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALK_2Z_Wa5kN2T6zf-fhJqaNRGHJ_b_uc',
    appId: '1:743191976125:android:0aaf37f0afff15536dbfd4',
    messagingSenderId: '743191976125',
    projectId: 'special-love-fa3eb',
    storageBucket: 'special-love-fa3eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALK_2Z_Wa5kN2T6zf-fhJqaNRGHJ_b_uc',
    appId: '1:743191976125:ios:0aaf37f0afff15536dbfd4',
    messagingSenderId: '743191976125',
    projectId: 'special-love-fa3eb',
    storageBucket: 'special-love-fa3eb.firebasestorage.app',
    iosBundleId: 'com.speciallove.anf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALK_2Z_Wa5kN2T6zf-fhJqaNRGHJ_b_uc',
    appId: '1:743191976125:macos:0aaf37f0afff15536dbfd4',
    messagingSenderId: '743191976125',
    projectId: 'special-love-fa3eb',
    storageBucket: 'special-love-fa3eb.firebasestorage.app',
    iosBundleId: 'com.speciallove.anf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALK_2Z_Wa5kN2T6zf-fhJqaNRGHJ_b_uc',
    appId: '1:743191976125:web:0aaf37f0afff15536dbfd4',
    messagingSenderId: '743191976125',
    projectId: 'special-love-fa3eb',
    authDomain: 'special-love-fa3eb.firebaseapp.com',
    storageBucket: 'special-love-fa3eb.firebasestorage.app',
  );
}